package com.example.demo.model;

public class Employee {

    // Basic Information
    private int id;
    private String name;
    private String email;

    // Contact & Identity
    private String phoneNumber;
    private String department;
    private String designation;

    // Administrative Details
    private double salary;
    private String joiningDate; // Could also use LocalDate
    private boolean isActive;

    // Miscellaneous
    private String reportingManager;

    // Constructors, Getters, and Setters (optional - can be auto-generated by your IDE)

    public Employee(int id, String name, String email, String phoneNumber, String department,
                    String designation, double salary, String joiningDate, boolean isActive,
                    String reportingManager) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.department = department;
        this.designation = designation;
        this.salary = salary;
        this.joiningDate = joiningDate;
        this.isActive = isActive;
        this.reportingManager = reportingManager;
    }

	@Override
	public String toString() {
		return "Employee [id=" + id + ", name=" + name + ", email=" + email + ", phoneNumber=" + phoneNumber
				+ ", department=" + department + ", designation=" + designation + ", salary=" + salary
				+ ", joiningDate=" + joiningDate + ", isActive=" + isActive + ", reportingManager=" + reportingManager
				+ "]";
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhoneNumber() {
		return phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getDesignation() {
		return designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public double getSalary() {
		return salary;
	}

	public void setSalary(double salary) {
		this.salary = salary;
	}

	public String getJoiningDate() {
		return joiningDate;
	}

	public void setJoiningDate(String joiningDate) {
		this.joiningDate = joiningDate;
	}

	public boolean isActive() {
		return isActive;
	}

	public void setActive(boolean isActive) {
		this.isActive = isActive;
	}

	public String getReportingManager() {
		return reportingManager;
	}

	public void setReportingManager(String reportingManager) {
		this.reportingManager = reportingManager;
	}

   
}
